---
- name: CSI Driver Helm Repo
  kubernetes.core.helm_repository:
    name: secrets-store-csi-driver
    repo_url: "https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts"
- name: CSI Driver Helm Chart
  kubernetes.core.helm:
    name: csi-secrets-store
    chart_ref: secrets-store-csi-driver/secrets-store-csi-driver
    release_namespace: kube-system
    values:
      syncSecret:
        enabled: true
      enableSecretRotation: true
- name: CSI Driver AWS Provider
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'aws-provider-installer.yaml') }}"
- name: Create CSI Driver Service Account
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'csi-service-account.yaml') | from_yaml }}"
- name: Create SecretProviderClass
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'aline-secrets.yaml') | from_yaml }}"
