---
- name: Deploy Terraform
  community.general.terraform:
    project_path: "{{ terraform_project_dir }}"
    variables_file: "{{ terraform_variables_file }}"
    force_init: true
    backend_config_files:
      - "{{ terraform_backend_config }}"
    workspace: "{{ terraform_workspace }}"
- name: Create Variables from Terraform
  changed_when: false
  ansible.builtin.shell: |
    echo "aline_secrets_role_arn: $(terraform -chdir=../terraform/resources output aline_secrets_role_arn)" > output.yaml
    echo "aline_secrets_arn: $(terraform -chdir=../terraform/resources output aline_secrets_arn)" >> output.yaml
    echo "eks_cluster_name: $(terraform -chdir=../terraform/resources output eks_name)" >> output.yaml
    echo "load_balancer_role_arn: $(terraform -chdir=../terraform/resources output load_balancer_role_arn)" >> output.yaml
    echo "autoscaler_role_arn: $(terraform -chdir=../terraform/resources output autoscaler_role_arn)" >> output.yaml
    echo "alb_certificate_arn: $(terraform -chdir=../terraform/resources output alb_certificate_arn)" >> output.yaml
    echo "cluster_name: $(terraform -chdir=../terraform/resources output eks_name)" >> output.yaml
