apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws 
  parameters:
    objects: |
      - objectName: 
        objectType: secretsmanager
        jmesPath: 
          - path: username
            objectAlias: dbusername
          - path: password 
            objectAlias: dbpassword 
  
  secretObjects:
    - secretName: aline-secrets
      type: Opaque
      data:
        - objectName: dbusername
          key: dbusername
        - objectName: dbpassword
          key: dbpassword
