apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: microservices
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ aline_secrets_arn }}"
        objectType: secretsmanager
        jmesPath:
          - path: username
            objectAlias: dbusername
          - path: password
            objectAlias: dbpassword
          - path: name
            objectAlias: dbname
          - path: host
            objectAlias: dbhost
          - path: port
            objectAlias: dbport
          - path: jwtsecretkey
            objectAlias: jwtsecretkey
          - path: encryptsecretkey
            objectAlias: encryptsecretkey
  secretObjects:
    - secretName: aline-secrets
      type: Opaque
      data:
        - objectName: dbusername
          key: dbusername
        - objectName: dbpassword
          key: dbpassword
        - objectName: dbname
          key: dbname
        - objectName: dbhost
          key: dbhost
        - objectName: dbport
          key: dbport
        - objectName: jwtsecretkey
          key: jwtsecretkey
        - objectName: encryptsecretkey
          key: encryptsecretkey
