{{- range $index, $microservice := .Values.microservices}}

{{- $loop_count := 1 }}
{{- if $microservice.green_tag }}
{{- $loop_count = 2 }}
{{- end }}

{{- range $i, $e := until $loop_count }}

{{- $tag := $microservice.tag | replace "." "-" }}
{{- if eq $i 1 }}
{{- $tag = $microservice.green_tag | replace "." "-" }}
{{- end}}

{{- $name := printf "%s-%s" $microservice.name $tag }}


apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  replicas: {{ $microservice.replicas }} 
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      serviceAccountName: aline-secrets-sa
      volumes:
        - name: secret-store-aline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"
      containers:
      - name: {{ $name }}
        {{- if $microservice.green_tag }}
        image: {{ $microservice.imagelocation }}{{ $microservice.name }}:{{ $microservice.green_tag }}
        {{- else }}
        image: {{ $microservice.imagelocation }}{{ $microservice.name }}:{{ $microservice.tag }}
        {{- end }}
        ports:
          - containerPort: 80
        volumeMounts:
          - name: secret-store-aline
            mountPath: "/mnt/secrets-store"
            readOnly: true
        env:
          - name: service_type
            value: {{ $microservice.name }}  
          - name: ENCRYPT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: aline-secrets
                key: encryptsecretkey 
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: aline-secrets
                key: jwtsecretkey 
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: aline-secrets
                key: dbusername 
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aline-secrets
                key: dbpassword 
          - name: DB_HOST
            valueFrom: 
              secretKeyRef: 
                name: aline-secrets
                key: dbhost 
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: aline-secrets
                key: dbport
          - name: DB_NAME
            valueFrom: 
              secretKeyRef:
                name: aline-secrets
                key: dbname 
          - name: APP_PORT
            value: '80'
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }} 
spec:
  type: NodePort
  selector:
    app: {{ $name }}
  ports:
    - protocol: TCP 
      port: 80 
      targetPort: 80 
---
{{- end }}
{{- end }}
  
